# Generated by Django 3.0.3 on 2020-02-19 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
        ('data_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['headline']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_written',
        ),
        migrations.RemoveField(
            model_name='article',
            name='words',
        ),
        migrations.AlterField(
            model_name='word',
            name='categories',
            field=models.ManyToManyField(related_name='words', to='sentiment.Category'),
        ),
        migrations.CreateModel(
            name='WordCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler.Article')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_handler.Word')),
            ],
        ),
    ]
