# Generated by Django 3.0.3 on 2020-02-19 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0002_auto_20200219_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_written',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
