# Generated by Django 3.0.3 on 2020-02-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0003_article_date_written'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordCount',
            new_name='WordsInArticleCount',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date_written']},
        ),
    ]
