# Generated by Django 3.0.3 on 2020-02-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0006_auto_20200224_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_written',
            field=models.DateTimeField(default='2020-02-26 13:41:14'),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(max_length=1024),
        ),
    ]
