# Generated by Django 3.0.3 on 2020-02-28 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0007_auto_20200226_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ticker', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='date_written',
            field=models.DateField(default='2020-02-28'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_handler.Asset'),
        ),
    ]
