# Generated by Django 3.0.3 on 2020-03-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0010_auto_20200301_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockprice',
            name='interday_return',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='ticker',
        ),
    ]
