# Generated by Django 3.0.3 on 2020-03-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0011_auto_20200301_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprice',
            name='interday_volatility',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
