# Generated by Django 3.0.3 on 2020-03-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0014_auto_20200301_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='negative_words',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
