# Generated by Django 3.0.3 on 2020-03-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0015_article_negative_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='negative_words',
            field=models.IntegerField(null=True),
        ),
    ]
