# Generated by Django 3.0.3 on 2020-03-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0016_auto_20200305_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contents',
            field=models.TextField(null=True),
        ),
    ]
