# Generated by Django 3.0.3 on 2020-03-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0019_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='article',
        ),
    ]
