# Generated by Django 3.0.3 on 2020-03-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0020_remove_line_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Line',
        ),
    ]
