# Generated by Django 3.0.3 on 2020-03-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0021_delete_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tokens',
            field=models.TextField(null=True),
        ),
    ]
