# Generated by Django 3.0.3 on 2020-03-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0022_article_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='smarter_positive_words',
            field=models.IntegerField(null=True),
        ),
    ]
