# Generated by Django 3.0.3 on 2020-03-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_neg_words', models.IntegerField()),
                ('total_article_words', models.IntegerField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
