# Generated by Django 3.0.3 on 2020-03-10 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0003_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=2000)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentiment.Model')),
            ],
        ),
    ]
