# Generated by Django 3.0.3 on 2020-03-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0004_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='line',
            field=models.TextField(),
        ),
    ]
