# Generated by Django 3.0.3 on 2020-03-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0005_auto_20200310_1752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Line',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
