# Generated by Django 3.0.3 on 2020-03-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0007_auto_20200325_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
