# Generated by Django 3.0.3 on 2020-04-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0009_auto_20200326_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word2VecModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('pathname', models.CharField(max_length=250)),
            ],
        ),
    ]
